### ISSUE TITLE
Error: No username configured

### ISSUE THREAD

**Issue by tonysprenk** [basdelfos/homebridge-tuya-web#1]
Installed Homebridge on a fresh macOS Mojave install, getting this error:

```
[7/24/2019, 10:51:30 PM] [TuyaWebPlatform] Initializing TuyaWebPlatform...
[7/24/2019, 10:51:30 PM] Error: No username configured
    at TuyaWebApi.getOrRefreshToken (/usr/local/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:170:15)
    at TuyaWebPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-tuya-web/index.js:55:25)
    at API.emit (events.js:203:13)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:103:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at internal/main/run_main_module.js:17:11

[7/24/2019, 10:51:30 PM] Homebridge is running on port 50826.
[7/24/2019, 10:51:30 PM] Got SIGTERM, shutting down Homebridge...
```

Config:
 
```
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "pin": "031-45-154"
  },
  
  
  "ports": {
    "start": 52100,
    "end": 52150,
    "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
  },
  "accessories": [
   
  ],

  "platforms": [
    

{
		"platform": "BroadlinkRM",
		"name": "Broadlink RM",
		"hideWelcomeMessage": true,
	        "accessories": [{
			"name": "TV On/Off",
			"type": "switch",
			"data": {
				"on": "2600500000012...",
				"off": "2600500000012..."
			}
		}]
	},
{
  "platform": "TuyaWebPlatform",
  "name": "TuyaWebPlatform",
  "options": [
    {
      "username": "xxxx@gmail.com",
      "password": "xxx",
      "countryCode": "31",
      "platform": "tuya"
    }
  ]
}
  ]
}
```

**Comment by chadman4** [comment]
Same issue with me. Not working.

**Comment by basdelfos** [comment]
The sample configuration in the Readme is wrong, it should be;
The square brackets after `options:` should not be there.

```
{
            "platform": "TuyaWebPlatform",
            "name": "TuyaWebPlatform",
            "options": {
                "username": "b.delfos@gmail.com",
                "password": "yfrHt*?{dh57<~",
                "countryCode": 31,
                "platform": "smart_life",
                "pollingInterval": 180
            }
}
```

Thanks for using the plugin and reporting issues you have found.
I will update the readme.
