### ISSUE TITLE
Error: Authentication fault, could not retrieve token

### ISSUE THREAD

**Issue by Haorak** [basdelfos/homebridge-tuya-web#12]
Hi,
I am running the tuya-web-platform and when i start homebridge i get this error : 
pi@raspberrypi:~/.homebridge $ homebridge
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
[2019-08-02, 10:27:16 p.m.] Loaded config.json with 0 accessories and 1 platforms.
[2019-08-02, 10:27:16 p.m.] ---
[2019-08-02, 10:27:17 p.m.] Loaded plugin: homebridge-tuya-web
[2019-08-02, 10:27:17 p.m.] Registering platform 'homebridge-tuya-web.TuyaWebPlatform'
[2019-08-02, 10:27:17 p.m.] ---
[2019-08-02, 10:27:17 p.m.] Loading 1 platforms...
[2019-08-02, 10:27:17 p.m.] [TuyaWebPlatform] Initializing TuyaWebPlatform platform...
Setup Payload:
X-HM://0023ISYWY7OBD
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:

[2019-08-02, 10:27:18 p.m.] [TuyaWebPlatform] Initializing TuyaWebPlatform...
[2019-08-02, 10:27:18 p.m.] Homebridge is running on port 51826.
[2019-08-02, 10:29:31 p.m.] [TuyaWebPlatform] Error: Authentication fault, could not retreive token.
    at Request.request [as _callback] (/usr/local/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:208:28)
    at self.callback (/usr/local/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:189:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
^C[2019-08-02, 10:34:38 p.m.] Got SIGINT, shutting down Homebridge...

It seems to read my config file correctly... I've verify twice and my credentials are good.

Thank you!

**Comment by Haorak** [comment]
Is there something I can provide to help the investigation? Please let me know.

**Comment by basdelfos** [comment]
Looking at the log, I noticed that there is a 2 minute gap between Initializing TuyaWebPlatform and the error. That means that the plugin is trying to connect to the Tuya Web API but timed out after 2 minutes. Can you make sure that Homebridge can reach the internet. Seems like it can not reach https://px1.tuyaeu.com.

**Comment by Haorak** [comment]
My raspberry is wire connected and on wifi... How can i validate that he can reach https://px1.tuyaeu.com ? Sorry if this is dumb question.

**Comment by basdelfos** [comment]
You can try to ping the host (command: `ping px1.tuyaeu.com` with the terminal in Homebridge, see the hamburger menu on the right top corner.

**Comment by Haorak** [comment]
Ok so i clearly can't ping px1.tuyaeu.com... I get 100% package loss. I've also tried px1.tuyaus.com and get the same result. What do i need to do next? Is there a config that i missed? Thank you for your support!

**Comment by basdelfos** [comment]
Ok, that is why the authentication times out. Either name resolving does not work or there is no internet connection. You can try to ping 18.194.69.163 (px1.tuyaeu.com). If that also results in packet loss, then there is no internet connection for sure.

**Comment by Haorak** [comment]
Ok I've tried pinging the ip adress and it works! I don't have any packet loss... So i guess it's the naming that does not work.  Where can i change that? Thank you!

**Comment by basdelfos** [comment]
Depends on which operating system you use. Best is to try Google it, there are numerous posts about how to set the DNS servers in an operating system. You can use the DNS sever ip addresses from your provider or use Google’ DNS servers 8.8.8.8 and 8.8.4.4.

As this gets off topic from this repository, do you mind if I close this issue?

**Comment by Haorak** [comment]
Ok I will search for this on google then. Hopefully that is the true issue, because i was trying to understand those error message, and i couldn't seem to find the repository that were mentioned. Path : 
/usr/local/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:208:28
I could not find homebridge-tuya-web in node_modules. Could this be another issue? If this is all related to the DNS not set up, then you can close this issue no problem. I really appreciate the time you take to answer all my questions!

**Comment by basdelfos** [comment]
As this seems to be a DNS issue, I will close this issue.
