### ISSUE TITLE
Error: The requested platform 'TuyaWebPlatform' was not registered by any plugin

### ISSUE THREAD

**Issue by denix666** [basdelfos/homebridge-tuya-web#2]

**Comment by denix666** [comment]
Jul 25 11:27:19 den-macmini homebridge[1221]: [2019-7-25 11:27:19] ERROR LOADING PLUGIN homebridge-tuya-web:
Jul 25 11:27:19 den-macmini homebridge[1221]: [2019-7-25 11:27:19] /usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:212
Jul 25 11:27:19 den-macmini homebridge[1221]:                     catch {
Jul 25 11:27:19 den-macmini homebridge[1221]:                           ^

**Comment by basdelfos** [comment]
Can you check if the fix works for you? Just run the plugin update from the Homebridge UI to install the latest version.

**Comment by denix666** [comment]
Previous error is gone, but now there is next error:

Jul 26 09:35:47 den-macmini homebridge[2335]: [2019-7-26 09:35:47] [TuyaWebPlatform] Initializing TuyaWebPlatform...
Jul 26 09:35:47 den-macmini homebridge[2335]: /usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:173
Jul 26 09:35:47 den-macmini homebridge[2335]:         throw new Error('No username configured');
Jul 26 09:35:47 den-macmini homebridge[2335]:         ^
Jul 26 09:35:47 den-macmini homebridge[2335]: Error: No username configured
Jul 26 09:35:47 den-macmini homebridge[2335]:     at TuyaWebApi.getOrRefreshToken (/usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:173:15)
Jul 26 09:35:47 den-macmini homebridge[2335]:     at TuyaWebPlatform.<anonymous> (/usr/lib/node_modules/homebridge-tuya-web/index.js:58:25)

But the credentials are provided like in example:

...
{
	"platform": "TuyaWebPlatform",
	"name": "TuyaWebPlatform",
	"options": [
		{
			"username": "denxxxxxxxxxxxxx@gmail.com",
			"password": "xxxxxxx",
			"countryCode": "370",
			"platform": "smart_life"
		}
	]
},
...

**Comment by basdelfos** [comment]
Aha, I now see what is wrong. I already suspected that the previous error was caused by something else.
With the initial upload a made an error in the sample configuration. The square brackets after “options:” shouldn’t be there. Remove the backets and it is probably fixed. Also see the README for updated sample configuration.

Gr. Bas

Outlook voor iOS<https://aka.ms/o0ukef> downloaden

________________________________
Van: Denis Salmanovich <notifications@github.com>
Verzonden: vrijdag, juli 26, 2019 8:42 AM
Aan: basdelfos/homebridge-tuya-web
CC: Bas Delfos; Comment
Onderwerp: Re: [basdelfos/homebridge-tuya-web] Error: The requested platform 'TuyaWebPlatform' was not registered by any plugin (#2)


Previous error is gone, but now there is next error:

Jul 26 09:35:47 den-macmini homebridge[2335]: [2019-7-26 09:35:47] [TuyaWebPlatform] Initializing TuyaWebPlatform...
Jul 26 09:35:47 den-macmini homebridge[2335]: /usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:173
Jul 26 09:35:47 den-macmini homebridge[2335]: throw new Error('No username configured');
Jul 26 09:35:47 den-macmini homebridge[2335]: ^
Jul 26 09:35:47 den-macmini homebridge[2335]: Error: No username configured
Jul 26 09:35:47 den-macmini homebridge[2335]: at TuyaWebApi.getOrRefreshToken (/usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:173:15)
Jul 26 09:35:47 den-macmini homebridge[2335]: at TuyaWebPlatform. (/usr/lib/node_modules/homebridge-tuya-web/index.js:58:25)

But the credentials are provided like in example:

...
{
"platform": "TuyaWebPlatform",
"name": "TuyaWebPlatform",
"options": [
{
"username": "denxxxxxxxxxxxxx@gmail.com<mailto:denxxxxxxxxxxxxx@gmail.com>",
"password": "xxxxxxx",
"countryCode": "370",
"platform": "smart_life"
}
]
},
...

**Comment by denix666** [comment]
Yes, it helped. Now errors not appear, but the device, configured in smart life app, also not appear in homekit. Do I have to add some more configuration?

**Comment by basdelfos** [comment]
If you have added Homebridge into the Home app on your iOS device, the device should automatically show up in the Home app. If you already did that, than maybe removing and adding Homebridge in the Home app could help.

**Comment by denix666** [comment]
I tried to remove and add back my home in homekit, remove all cache files, switch homebridge username, but this not helped. I see all my devices, except devices from smart life app :-( Also I using homebridge-config-ui-x and can see all devices from the config web ui, but there are no devices form the smart life too....

**Comment by basdelfos** [comment]
Strange, I have no other clue why this isn't working for you. It looks like the plugin and homebridge successfully detected and registered the devices as you can see the devices in the Accessories tab in the config web ui.

**Comment by denix666** [comment]
This is some warning from the log:
Jul 27 20:27:22 den-macmini homebridge[16306]: [2019-7-27 20:27:22] [TuyaWebPlatform] Initializing TuyaWebPlatform...
Jul 27 20:27:22 den-macmini homebridge[16306]: (node:16306) [DEP0025] DeprecationWarning: sys is deprecated. Use util instead.
Jul 27 20:27:22 den-macmini homebridge[16306]: [2019-7-27 20:27:22] Homebridge is running on port 51826.

Also I saw here: https://github.com/basdelfos/homebridge-tuya-web/blob/fbbe0445b99224c6ec9f54900dda97f1e01549d2/lib/tuyawebapi.js#L36 that "tuya" platform is hardcoded. Tried to change it to smarl_life, but there was nothing changed...

Can I somehow to enable the debug mode of this plugin maybe?

**Comment by basdelfos** [comment]
This `tuyaPlaform = 'tuya'` means that Tuya is the default when no platform is specified.

**Comment by basdelfos** [comment]
You can enable debug in Homebridge by specifying option `-D` in the commandline.

E.g. `> homebridge -D`
