### ISSUE TITLE
Does not appear to be enumerate and get info on devices. Test code errors.

### ISSUE THREAD

**Issue by shanelilley** [basdelfos/homebridge-tuya-web#25]
Hi,
I have found that I have 3 devices via Smart Life, and upon attempting to use the plugin I receive the following error in Homebridge start up.

[2019-8-30 15:43:40] TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:50:12)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)

Then if I try the test module I receive the following output - 

root@testingpie:/usr/local/lib/node_modules/homebridge-tuya-web/test# mocha tuyawebapi_test.js

  ․․․․(node:6276) UnhandledPromiseRejectionWarning: Error: Invalid payload in response:
    at sendRequestJson (/usr/local/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:119:20)
    at sendRequest (/usr/local/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:309:11)
    at Request.request [as _callback] (/usr/local/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:295:11)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:6276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6276) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
․․

  5 passing (6s)
  1 failing

  1) TuyaWebApi get device state should get the state of a device:
     Error: timeout of 2000ms exceeded
      at Timeout.<anonymous> (/usr/lib/nodejs/mocha/lib/runnable.js:139:19)
      at ontimeout (timers.js:482:11)
      at tryOnTimeout (timers.js:317:5)
      at Timer.listOnTimeout (timers.js:277:5)

Any help greatly appreciated! I am really hoping to use your plugin to bring these devices in to Homebridge. 

Kind regards,
Shane

**Comment by basdelfos** [comment]
The first error seems to be a more general Homebridge error, could be that there is a fault in the config or something.

Second error seems to be caused by a timeout. Make sure the at the server that is running Homebridge is able to reach the internet. Try to ping px1.tuyaeu.com if that doesn't work, that something in the configuration of the server or network is causing the issue.

**Comment by shanelilley** [comment]
many thanks. I can definitely get to px1.tuyaeu.com... is it possible perhaps that I'm in Asia/Pacific region I should be going to more local server? This one appears to be EU

This is the line that bothers me - it does not appear to be handled... 
  ․․․․(node:3426) UnhandledPromiseRejectionWarning: Error: Invalid payload in response:
