### ISSUE TITLE
[23/09/2019, 21:22:42] Error: No valid token

### ISSUE THREAD

**Issue by samsonrosen** [basdelfos/homebridge-tuya-web#33]
Hello! The plugin works brilliantly, but now and then homebridge crashes with the following error:

```
[23/09/2019, 21:22:42] Error: No valid token
    at TuyaWebApi.discoverDevices (/usr/local/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:53:13)
    at TuyaWebApi.getAllDeviceStates (/usr/local/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:88:17)
    at TuyaWebPlatform.refreshDeviceStates (/usr/local/lib/node_modules/homebridge-tuya-web/index.js:89:21)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tuya-web/index.js:77:18)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

Since this error I have updated to homebridge-tuya-web@0.1.7 but not had this error yet (only an hour ago). Is there anything I can do to help provide more info or resolve the issue?

```
  "platform": "TuyaWebPlatform",
      "name": "TuyaWebPlatform",
      "options":
        {
          "username": "MOBILENUMBER",
          "password": "PASSWORD",
          "countryCode": "44",
          "platform": "tuya",
          "pollingInterval": 10
        }
```

**Comment by uberfunk** [comment]
I get this same error once in a while. No idea what causes it or how to solve it. Were you able to resolve it somehow?

**Comment by samsonrosen** [comment]
I'm not, I always update the package in hope the issue goes away.
