### ISSUE TITLE
Error: Authentication fault, could not retreive token. (Network not started yet)

### ISSUE THREAD

**Issue by neilmorton** [basdelfos/homebridge-tuya-web#38]
I am seeing the following error after restarting a raspberry pi running HomeBridge with homebridge-tuya-web.

```
Oct 14 10:55:25 rpil1 homebridge[309]: [10/14/2019, 10:55:25 AM] [TuyaWebPlatform] Error: Authentication fault, could not retreive token.
Oct 14 10:55:25 rpil1 homebridge[309]:     at Request.request [as _callback] (/usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:210:28)
Oct 14 10:55:25 rpil1 homebridge[309]:     at self.callback (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:185:22)
Oct 14 10:55:25 rpil1 homebridge[309]:     at Request.emit (events.js:198:13)
Oct 14 10:55:25 rpil1 homebridge[309]:     at Request.onRequestError (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:881:8)
Oct 14 10:55:25 rpil1 homebridge[309]:     at ClientRequest.emit (events.js:198:13)
Oct 14 10:55:25 rpil1 homebridge[309]:     at TLSSocket.socketErrorListener (_http_client.js:392:9)
Oct 14 10:55:25 rpil1 homebridge[309]:     at TLSSocket.emit (events.js:198:13)
Oct 14 10:55:25 rpil1 homebridge[309]:     at emitErrorNT (internal/streams/destroy.js:91:8)
Oct 14 10:55:25 rpil1 homebridge[309]:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
Oct 14 10:55:25 rpil1 homebridge[309]:     at process._tickCallback (internal/process/next_tick.js:63:19)
```

It is apparent that when starting homebridge, if the network is not yet available, homebridge-tuya-web is unable to authenticate and doesn't appear to retry. As a result the service never connects to the Web API.

Having followed the instructions [here](https://github.com/nfarina/homebridge/wiki/Install-Homebridge-on-Raspbian) to create a service for homebridge:

```
cat >/etc/systemd/system/homebridge.service <<EOL
[Unit]
Description=Homebridge
After=syslog.target network-online.target

[Service]
Type=simple
User=homebridge
EnvironmentFile=/etc/default/homebridge
ExecStart=$(which homebridge) \$HOMEBRIDGE_OPTS
Restart=on-failure
RestartSec=3
KillMode=process
CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT CAP_CHOWN CAP_FOWNER CAP_DAC_OVERRIDE CAP_AUDIT_WRITE CAP_SYS_ADMIN
AmbientCapabilities=CAP_NET_RAW

[Install]
WantedBy=multi-user.target
EOL
```

It is clear that `After=syslog.target network-online.target` doesn't wait for connectivity to occur.

I have worked around this by adding another line to the homebridge.service file:
```
ExecStartPre=/bin/sh -c 'until ping -c1 github.com; do sleep 5; done;'
```

This ensures that the pi is able to communicate with the internet prior to starting, however it would be good to include a routine to automatically re-check this within homebridge-tuya-web and retry after a delay, as if the service dropped at any stage the check would run then also.

[homebridge-nest](https://github.com/chrisjshull/homebridge-nest) provides the ability to do this so I think a similar approach could be used.

**Comment by peros550** [comment]
this is a nice workaround, but as you suggested it needs to be fixed in the proper way. 
In case there is no internet after a power outage for some reason, the whole homebridge installation and all its accessories will not be available , at least locally which is an issue.
