### ISSUE TITLE
Cannot read property 'devices' of null

### ISSUE THREAD

**Issue by g30r93g** [basdelfos/homebridge-tuya-web#40]
TypeError: Cannot read property 'devices' of null

Occurred when initialising the platform. Any clues?

**Comment by g30r93g** [comment]
[Tuya] Initializing TuyaWebPlatform...
Oct 24 13:48:04 raspberrypi homebridge[890]: [10/24/2019, 1:48:04 PM] TypeError: Cannot read property 'devices' of null
Oct 24 13:48:04 raspberrypi homebridge[890]:     at TuyaLan.discoverDevices (/usr/local/lib/node_modules/homebridge-tuya-lan/index.js:47:21)
Oct 24 13:48:04 raspberrypi homebridge[890]:     at API.TuyaLan.api.on (/usr/local/lib/node_modules/homebridge-tuya-lan/index.js:39:18)
Oct 24 13:48:04 raspberrypi homebridge[890]:     at API.emit (events.js:203:15)
Oct 24 13:48:04 raspberrypi homebridge[890]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:103:13)
Oct 24 13:48:04 raspberrypi homebridge[890]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Oct 24 13:48:04 raspberrypi homebridge[890]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Oct 24 13:48:04 raspberrypi homebridge[890]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
Oct 24 13:48:04 raspberrypi homebridge[890]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Oct 24 13:48:04 raspberrypi homebridge[890]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Oct 24 13:48:04 raspberrypi homebridge[890]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

**Comment by g30r93g** [comment]
Turned out it was the old plugin I was replacing this one with lol
