### ISSUE TITLE
No valid response from API

### ISSUE THREAD

**Issue by palla89** [basdelfos/homebridge-tuya-web#46]
Hi, I'm using this awesome plugin since it was released without any issue. Today (yesterday everything was working fine), without any change on my side, all the toggles stopped working.

This is the error I got:

```
[11/12/2019, 9:58:28 AM] [TuyaWebPlatform] Error retrieving devices states Error: No valid response from API
    at sendRequestJson (/homebridge/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:78:18)
    at sendRequest (/homebridge/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:309:11)
    at Request.request [as _callback] (/homebridge/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:295:11)
    at Request.self.callback (/homebridge/node_modules/homebridge-tuya-web/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-tuya-web/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-tuya-web/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
```

From the official Tuya app, everything is working well. Here's my configuration:

`{
            "platform": "TuyaWebPlatform",
            "name": "TuyaWebPlatform",
            "options": {
                "username": "mail",
                "password": "pwd",
                "countryCode": "39",
                "platform": "tuya",
                "pollingInterval": 10
            }
        }`

Anyone else with this error?

UPDATE: It could be an error on their side, also the official Alexa skill is not working :D It's ok only from the Tuya app!

**Comment by palla89** [comment]
Update 2: Strange enough, I read about this homebridge's issue: https://github.com/nfarina/homebridge/issues/2348

and rebooting my router "fixed" the problem, at least for now, so the good news is that it's not a plugin problem, hooray! 😂
