### ISSUE TITLE
[TuyaWebPlatform] Error retrieving devices states TypeError

### ISSUE THREAD

**Issue by josleng** [basdelfos/homebridge-tuya-web#49]
hello everybody, I have a led tv working with Tuya app.
i'have installed the web plugin in homebridge, I can see the led on my iPhone but
on homebridge I have this error:
[TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16/11/2019, 12:52:44] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16/11/2019, 12:52:54] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16/11/2019, 12:53:04] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16/11/2019, 12:53:14] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16/11/2019, 12:53:24] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16/11/2019, 12:53:34] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16/11/2019, 12:53:43] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16/11/2019, 12:53:54] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16/11/2019, 12:54:04] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16/11/2019, 12:54:14] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16/11/2019, 12:54:24] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
at LightAccessory.updateState (/usr/local/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:225:39)
at LightAccessory.updateAccessory (/usr/local/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:10)
at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:95:42
at processTicksAndRejections (internal/process/task_queues.js:93:5)
[

someone can help me?

**Comment by posul** [comment]
I also have this issue. Any update?

**Comment by Theorian** [comment]
Same here, annoying me enough to consider fixing it myself.
