### ISSUE TITLE
(node:17112) UnhandledPromiseRejectionWarning: Error: No valid token

### ISSUE THREAD

**Issue by samsonrosen** [basdelfos/homebridge-tuya-web#5]
Hi! I'm getting the following error with the following config:

```
(node:17112) UnhandledPromiseRejectionWarning: Error: No valid token
    at TuyaWebApi.discoverDevices (/usr/local/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:50:13)
    at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:62:27
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

(node:17112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

```
{
  "platform": "TuyaWebPlatform",
  "name": "TuyaWebPlatform",
  "options":
    {
      "username": "USERNAME",
      "password": "PASSWORD",
      "countryCode": "44",
      "platform": "smart_life",
      "pollingInterval": 10
    }
  },
```

**Comment by basdelfos** [comment]
See #4

**Comment by samsonrosen** [comment]
Thank you!! Your plugin was super simple to setup - I tried the others but it required a bit to much manual work to get the ID's. After the update and checking my credentials it's all working.
