### ISSUE TITLE
Invalid Payload In Response

### ISSUE THREAD

**Issue by GioCirque** [basdelfos/homebridge-tuya-web#54]
So, this started happening today.

```shell
[12/2/2019, 10:24:22 PM] [TuyaWebPlatform] [SET][Main Hallway Light] Characteristic.On Error: Error: Invalid payload in response:
at /usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:161:20
at /usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:309:11
at Request._callback (/usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:295:11)
at Request.self.callback (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:185:22)
at Request.emit (events.js:210:5)
at Request.<anonymous> (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:1161:10)
at Request.emit (events.js:210:5)
at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:299:28)
at IncomingMessage.emit (events.js:215:7)
at endReadableNT (_stream_readable.js:1200:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)

[12/2/2019, 10:24:22 PM] [TuyaWebPlatform] [SET][Laundry Room Light] Characteristic.On Error: Error: Invalid payload in response:
at /usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:161:20
at /usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:309:11
at Request._callback (/usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:295:11)
at Request.self.callback (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:185:22)
at Request.emit (events.js:210:5)
at Request.<anonymous> (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:1161:10)
at Request.emit (events.js:210:5)
at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:299:28)
at IncomingMessage.emit (events.js:215:7)
at endReadableNT (_stream_readable.js:1200:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)

[12/2/2019, 10:24:22 PM] [TuyaWebPlatform] [SET][Counter Lights] Characteristic.Hue Error: Error: Invalid payload in response:
at /usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:161:20
at /usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:309:11
at Request._callback (/usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:295:11)
at Request.self.callback (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:185:22)
at Request.emit (events.js:210:5)
at Request.<anonymous> (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:1161:10)
at Request.emit (events.js:210:5)
at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:299:28)
at IncomingMessage.emit (events.js:215:7)
at endReadableNT (_stream_readable.js:1200:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)

[12/2/2019, 10:24:22 PM] [TuyaWebPlatform] [SET][Kitchen Lights] Characteristic.Saturation Error: Error: Invalid payload in response:
at /usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:161:20
at /usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:309:11
at Request._callback (/usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:295:11)
at Request.self.callback (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:185:22)
at Request.emit (events.js:210:5)
at Request.<anonymous> (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:1161:10)
at Request.emit (events.js:210:5)
at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:299:28)
at IncomingMessage.emit (events.js:215:7)
at endReadableNT (_stream_readable.js:1200:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)

[12/2/2019, 10:24:22 PM] [TuyaWebPlatform] [SET][Counter Lights] Characteristic.Saturation Error: Error: Invalid payload in response:
at /usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:161:20
at /usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:309:11
at Request._callback (/usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:295:11)
at Request.self.callback (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:185:22)
at Request.emit (events.js:210:5)
at Request.<anonymous> (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:1161:10)
at Request.emit (events.js:210:5)
at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:299:28)
at IncomingMessage.emit (events.js:215:7)
at endReadableNT (_stream_readable.js:1200:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)

[12/2/2019, 10:24:22 PM] [TuyaWebPlatform] [SET][Main Hallway Light] Characteristic.Brightness Error: Error: Invalid payload in response:
at /usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:161:20
at /usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:309:11
at Request._callback (/usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:295:11)
at Request.self.callback (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:185:22)
at Request.emit (events.js:210:5)
at Request.<anonymous> (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:1161:10)
at Request.emit (events.js:210:5)
at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:299:28)
at IncomingMessage.emit (events.js:215:7)
at endReadableNT (_stream_readable.js:1200:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)

[12/2/2019, 10:24:22 PM] [TuyaWebPlatform] [SET][Kitchen Lights] Characteristic.Hue Error: Error: Invalid payload in response:
at /usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:161:20
at /usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:309:11
at Request._callback (/usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:295:11)
at Request.self.callback (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:185:22)
at Request.emit (events.js:210:5)
at Request.<anonymous> (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:1161:10)
at Request.emit (events.js:210:5)
at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:299:28)
at IncomingMessage.emit (events.js:215:7)
at endReadableNT (_stream_readable.js:1200:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by marksthomas** [comment]
Yeah I'm getting this too. I think it's just an API hiccup. Stuff still works here.
