### ISSUE TITLE
ETIMEDOUT

### ISSUE THREAD

**Issue by Radstake** [basdelfos/homebridge-tuya-web#87]
Hi,

I've been using plugin for long time, always working nicely.
But lately it times out after x time.
After a reboot it's fine, but starting to go wrong soon after that.

```
[2020-4-27 10:25:43 PM] [TuyaWebPlatform] Error retrieving devices states { Error: connect ETIMEDOUT 3.123.103.156:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '3.123.103.156',
  port: 443 }
```

**Comment by doublezerosept** [comment]
Hi, same issue for me but for a different IP address:
[4/28/2020, 11:20:21 AM] [TuyaWebPlatform] Error retrieving devices states Error: connect ETIMEDOUT 52.27.146.219:443
     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {
   errno: 'ETIMEDOUT',
   code: 'ETIMEDOUT',
   syscall: 'connect',
   address: '52.27.146.219',
   port: 443
 }

This looks like it started on Apr 25 22:05:05 (at least for me)
