### ISSUE TITLE
All Tuya devices suddenly stopped working today ?

### ISSUE THREAD

**Issue by steveharris08** [basdelfos/homebridge-tuya-web#88]
Today for unknown reason all my Tuya connected devices won’t work through homebridge. They still work through the Tuya app ? If I change them in the Tuya app the status still changes in homebridge ? Any suggestions please

**Comment by tbrek** [comment]
Mine also stopped today:

Here's what I've got in logs:
`[5/27/2020, 11:56:56 AM] [TuyaWebPlatform] Error: Authentication fault, could not retreive token.
    at Request.request [as _callback] (/usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:210:28)
    at self.callback (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.onRequestError (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

**Comment by tbrek** [comment]
Rebooted it and it started working again. @steveharris08 try restarting the service.
