### ISSUE TITLE
Error Retrieving Devices states

### ISSUE THREAD

**Issue by rcoletti116** [basdelfos/homebridge-tuya-web#89]
Started getting this error. HomeKit still allows me to control the devices, but Homebridge shows API errors.
---
6/12/2020, 5:23:03 PM] [TuyaWebPlatform] Error retrieving devices states Error: No valid response from API
    at sendRequestJson (/usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:78:18)
    at sendRequest (/usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:309:11)
    at Request.request [as _callback] (/usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:295:11)
    at Request.self.callback (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by blazzik** [comment]
Me too... same “no valid response from API” anyone up to fork this or is there another homebridge package that works with these devices

**Comment by steveb85** [comment]
I’m getting this as well, however, i can’t see any accessories that aren’t working, just seeing the error in my logs

**Comment by rcoletti116** [comment]
Same @steveb85 my devices are working just fine, but the logs are filled with this junk.

I've tried a few forks and all are the same. I've opened up the same issue on another that seems to still be active in development: https://github.com/milo526/homebridge-tuya-web/issues/4#issuecomment-643657679

**Comment by steveb85** [comment]
@rcoletti116 thanks, good to know we’re in the same boat, I’ll follow along and help if i can!

**Comment by thepotterfamily** [comment]
Please see pull request for other package - https://github.com/milo526/homebridge-tuya-web/pull/5

**Comment by fratton** [comment]
I create a fork with "Scene" and i reduce this error: https://github.com/fratton/homebridge-tuya-web/

**Comment by Galiwyx** [comment]
> 
> 
> I create a fork with "Scene" and i reduce this error: https://github.com/fratton/homebridge-tuya-web/

Thank you very much !!!

**Comment by Faisalthe01** [comment]
> I create a fork with "Scene" and i reduce this error: https://github.com/fratton/homebridge-tuya-web/

Hi buddy, can i know the changes you made to support Scene as Switches? i am using a different Fork and would want to add your code into to Support Scene as Swtiches. Thank you

**Comment by Raiden38** [comment]
I have the same issue. A reboot did not help...
